plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mydesk.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mydesk.ai'
        minSdk 26
        targetSdk 35
        versionCode 20900
        versionName '0.2.9'
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }
}
