plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mydesk.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mydesk.ai'
        minSdk 26
        targetSdk 34
        versionCode 30100
        versionName '0.3.1'
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }
}
